stages:
  - test

test:linux:
  stage: test
  image: golang:latest
  variables:
    GIT_URL: git.janstun.com
    GOPATH: /go
    PROJECT_DIR: $GOPATH/src/$GITLAB_URL/$CI_PROJECT_NAMESPACE
  script:
    - PROJECT_DIR=${PROJECT_DIR/janstun\//}
    - mkdir -p $PROJECT_DIR
    - cp -r $CI_PROJECT_DIR $PROJECT_DIR/$CI_PROJECT_NAME
    - cd $PROJECT_DIR/$CI_PROJECT_NAME
    - git config --global url."https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/janstun/".insteadOf "https://$GIT_URL/"
    - go get -v -t .
    - go test -cover .
